### ISSUE TITLE
Aggregator can't generate categories, no relevant debug output is written

### ISSUE THREAD

**Issue by georgebax** [eclipse-cbi/p2repo-aggregator#16]
Hi, I have the following issue: The aggregator fails even with the following targetrepo file - I have tried with all the versions listed in https://download.eclipse.org/cbi/updates/p2-aggregator/products/milestone/latest/index.html. In the expected eclipse log file this is the stackatrace at the end: 

```
java.lang.NullPointerException
	at org.eclipse.equinox.internal.p2.persistence.XMLWriter.writeProperty(XMLWriter.java:250)
	at java.base/java.util.Map.forEach(Map.java:661)
	at org.eclipse.equinox.internal.p2.persistence.XMLWriter.writeProperties(XMLWriter.java:242)
	at org.eclipse.equinox.internal.p2.persistence.XMLWriter.writeProperties(XMLWriter.java:232)
	at org.eclipse.equinox.internal.p2.metadata.repository.io.MetadataWriter.writeInstallableUnit(MetadataWriter.java:78)
	at org.eclipse.equinox.internal.p2.metadata.repository.io.MetadataWriter.writeInstallableUnits(MetadataWriter.java:49)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryIO$Writer.write(MetadataRepositoryIO.java:145)
	at org.eclipse.equinox.internal.p2.metadata.repository.MetadataRepositoryIO.write(MetadataRepositoryIO.java:94)
	at org.eclipse.equinox.internal.p2.metadata.repository.LocalMetadataRepository.save(LocalMetadataRepository.java:284)
	at org.eclipse.equinox.internal.p2.metadata.repository.LocalMetadataRepository.addInstallableUnits(LocalMetadataRepository.java:111)
	at org.eclipse.cbi.p2repo.aggregator.engine.CategoriesGenerator.run(CategoriesGenerator.java:288)
	at org.eclipse.cbi.p2repo.aggregator.engine.Builder.runCategoriesRepoGenerator(Builder.java:1769)
	at org.eclipse.cbi.p2repo.aggregator.engine.Builder.run(Builder.java:1719)
	at org.eclipse.cbi.p2repo.aggregator.engine.Builder.run(Builder.java:1764)
	at org.eclipse.cbi.p2repo.cli.AbstractCommand.run(AbstractCommand.java:143)
	at org.eclipse.cbi.p2repo.cli.Headless.run(Headless.java:166)
	at org.eclipse.cbi.p2repo.cli.Headless.start(Headless.java:201)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:136)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:402)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:659)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:596)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1467)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1440)
```

This happens in this point in the maven output log : 
```
Verifying config win32,win32,x86...
Verifying config win32,win32,x86_64...
Verifying config macosx,cocoa,x86_64...
Verifying config macosx,cocoa,aarch64...
Verifying config linux,gtk,x86_64...
Verified config win32,win32,x86...
Verified config win32,win32,x86_64...
Verified config macosx,cocoa,x86_64...
Verified config macosx,cocoa,aarch64...
Verified config linux,gtk,x86_64...
Verification successful
Done. Took 0 seconds
Starting generation of categories
Build failed! Exception was java.lang.NullPointerException:
java.lang.NullPointerException
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```
 
```
targetrepo.aggr: 

<?xml version="1.0" encoding="UTF-8"?>
<aggregator:Aggregation xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:aggregator="http://www.eclipse.org/cbi/p2repo/2011/aggregator/1.1.0" label="Target Platform Repository" buildRoot="./target/repository" packedStrategy="SKIP">
  <validationSets label="MyProject">
    <contributions label="Eclipse.org">
    </contributions>
  </validationSets>
  <configurations/>
  <configurations architecture="x86_64"/>
  <configurations operatingSystem="macosx" windowSystem="cocoa" architecture="x86_64"/>
  <configurations operatingSystem="macosx" windowSystem="cocoa" architecture="aarch64"/>
  <configurations operatingSystem="linux" windowSystem="gtk" architecture="x86_64"/>
  <customCategories identifier="3rd party" label="3rd party"/>
</aggregator:Aggregation>

```

This is the relevant content in my pom.xml : 

```
            <plugin>
                <groupId>org.eclipse.tycho.extras</groupId>
                <artifactId>tycho-eclipserun-plugin</artifactId>
                <executions>
                    <execution>
                        <goals>
                            <goal>eclipse-run</goal>
                        </goals>
                        <phase>prepare-package</phase>
                    </execution>
                </executions>
                <configuration>
                    <!-- DO NOT FORMAT THE FOLLOWING LINE, IT MUST BE ON ONE LINE -->
                    <appArgLine>-application org.eclipse.cbi.p2repo.cli.headless aggregate --eclipseLogLevel DEBUG --logLevel DEBUG --buildModel targetrepo.aggr</appArgLine>
                    <dependencies>
                        <dependency>
                            <artifactId>org.eclipse.cbi.p2repo.aggregator.engine.feature</artifactId>
                            <type>eclipse-feature</type>
                        </dependency>
                        <dependency>
                            <artifactId>org.eclipse.equinox.core.feature</artifactId>
                            <type>eclipse-feature</type>
                        </dependency>
                        <dependency>
                            <artifactId>org.eclipse.equinox.p2.core.feature</artifactId>
                            <type>eclipse-feature</type>
                        </dependency>
                    </dependencies>
                    <repositories>
                        <repository>
                            <id>cbi-aggregator</id>
                            <layout>p2</layout>
                            <url>https://download.eclipse.org/cbi/updates/p2-aggregator/products/nightly/N202301181123</url>
                        </repository>
                    </repositories>
                </configuration>
            </plugin>
```

This only seems to happen after ugrading to the latest builds, previously I was using release 4.7 and tycho 1.7.X - now it's tycho 2.7.5, which also looks to be the tycho version that is internally used by the aggregator.

**Comment by georgebax** [comment]
It looks like this line in the targetrepo.aggr was the problem, I don't know why it wasn't a problem in the 4.7 release though.

**Comment by merks** [comment]
I know the handling of that was somewhat changed to changed.  What specifically did you need to do to "fix" the problem?

**Comment by georgebax** [comment]
It looks like we didn't need this "3rd party" custom category, I just deleted it and the mirrored artifacts seem to be the same. Other than that, I'm not sure what exactly the issue was - could be that this customCategory with this id needed to be defined somewhere else (?)

**Comment by merks** [comment]
It looks like the null description is causing the problem:

![image](https://github.com/eclipse-cbi/p2repo-aggregator/assets/208716/6bc0f6ac-060d-4188-a26d-119a0973a24b)

Maybe something in p2 changed.   I need to run right now, but when I get back I'll look at why this property is populated with a null value; we should avoid doing that when the model's description is null...

**Comment by georgebax** [comment]
Yes I see, in my opinion at least a more informative debug output about the null property would help.

**Comment by merks** [comment]
In the past, a property with a null value was simply not written out, but now p2 has added some logic to the serialization that assumes the value is not null.   That logic should have been better guarded.  I fixed the problem in the aggregator by avoiding to set the properties to null values in the first place.  The latest nightly build already has the fix.

Thank you for reporting the problem with easy-to-reproduce details.

**Comment by georgebax** [comment]
You're welcome, and thanks for the timely replies @merks
